/* test_tools.c — function calling, both directions, with no checkpoint.
 *
 * Two properties are pinned here, and neither is cosmetic:
 *
 *  1. The prompt we render for a tool-calling turn is BYTE-IDENTICAL to what
 *     HF's apply_chat_template produces. A model that sees a `# Tools` block
 *     spelled slightly differently from the one it was trained on still
 *     answers — just worse, and nothing in the output says why. The fixture is
 *     generated by tools/gen_chat_fixture.py and committed, so this runs in CI
 *     with no Python and no weights.
 *
 *  2. What comes back out is parsed conservatively. A malformed call must be
 *     reported as malformed, never turned into a plausible-looking one: a
 *     function call is something a caller EXECUTES, so guessing at the JSON is
 *     the one failure mode with consequences outside this process.
 *
 * SPDX-License-Identifier: MIT */
#include "template.h"
#include "tools.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int failures, checks;

static void check(const char *what, int ok, const char *detail) {
    checks++;
    if (ok) printf("ok   %s\n", what);
    else { printf("FAIL %s\n     <- %s\n", what, detail ? detail : ""); failures++; }
}

/* ── the fixture ───────────────────────────────────────────────────────────*/

#define MAX_CASES 32
static char *fx_name[MAX_CASES];
static char *fx_text[MAX_CASES];
static size_t n_fx;

static size_t unescape(char *s) {
    char *w = s;
    for (char *r = s; *r; r++) {
        if (*r != '\\') { *w++ = *r; continue; }
        switch (*++r) {
            case 'n':  *w++ = '\n'; break;
            case 't':  *w++ = '\t'; break;
            case 'r':  *w++ = '\r'; break;
            case '\\': *w++ = '\\'; break;
            default:   *w++ = '\\'; *w++ = *r; break;
        }
    }
    *w = '\0';
    return (size_t)(w - s);
}

static int load_fixture(const char *path) {
    FILE *f = fopen(path, "rb");
    if (!f) return -1;

    char line[16384];
    while (fgets(line, sizeof line, f) && n_fx < MAX_CASES) {
        size_t len = strlen(line);
        while (len && (line[len - 1] == '\n' || line[len - 1] == '\r')) line[--len] = '\0';
        if (!len) continue;

        char *tab = strchr(line, '\t');
        if (!tab) continue;
        *tab = '\0';

        fx_name[n_fx] = strdup(line);
        fx_text[n_fx] = strdup(tab + 1);
        unescape(fx_text[n_fx]);
        n_fx++;
    }
    fclose(f);
    return 0;
}

static const char *expected(const char *name) {
    for (size_t i = 0; i < n_fx; i++)
        if (!strcmp(fx_name[i], name)) return fx_text[i];
    return NULL;
}

/* Show the first difference rather than two walls of text. */
static void diff_report(const char *name, const char *want, const char *got) {
    size_t i = 0;
    while (want[i] && got[i] && want[i] == got[i]) i++;
    const size_t from = i > 30 ? i - 30 : 0;
    printf("     %s: first difference at byte %zu\n", name, i);
    printf("       want ...%.60s\n", want + from);
    printf("       got  ...%.60s\n", got + from);
}

static void render_case(const char *name, const mynah_slm_message *msgs, size_t n,
                        const mynah_slm_tool *tools, size_t n_tools,
                        mynah_slm_think think) {
    const char *want = expected(name);
    if (!want) { check(name, 0, "case missing from the fixture"); return; }

    const long need = mynah_slm_render_chat_tools(msgs, n, tools, n_tools, think, NULL, 0);
    if (need < 0) { check(name, 0, "render returned an error"); return; }

    char *got = malloc((size_t)need + 1);
    mynah_slm_render_chat_tools(msgs, n, tools, n_tools, think, got, (size_t)need + 1);

    const int ok = strcmp(want, got) == 0;
    check(name, ok, "differs from HF");
    if (!ok) diff_report(name, want, got);

    /* The sizing pass must agree with what was written, or every caller that
     * mallocs from it is one byte from a truncation. */
    check("  ... sizing pass matches", (size_t)need == strlen(got), NULL);
    free(got);
}

/* ── the schemas, spelled the way json.dumps would ─────────────────────────*/

static const mynah_slm_tool WEATHER = {
    .name = "get_weather",
    .description = "Get the current weather in a given city",
    .parameters =
        "{\"type\": \"object\", \"properties\": {\"city\": {\"type\": \"string\", "
        "\"description\": \"The city name\"}, \"unit\": {\"type\": \"string\", "
        "\"enum\": [\"celsius\", \"fahrenheit\"]}}, \"required\": [\"city\"]}",
};
static const mynah_slm_tool PING = { .name = "ping" };

static void test_rendering(void) {
    const mynah_slm_tool both[2] = { WEATHER, PING };

    mynah_slm_message user = { MYNAH_SLM_ROLE_USER, "What is the weather in Verona?", NULL, 0 };
    render_case("plain", &user, 1, NULL, 0, MYNAH_SLM_THINK_OFF);

    mynah_slm_message maths = { MYNAH_SLM_ROLE_USER, "Quanto fa 17+25?", NULL, 0 };
    render_case("plain_think", &maths, 1, NULL, 0, MYNAH_SLM_THINK_ON);

    mynah_slm_message sys2[2] = {
        { MYNAH_SLM_ROLE_SYSTEM, "You are terse.", NULL, 0 },
        { MYNAH_SLM_ROLE_USER,   "Hi",             NULL, 0 },
    };
    render_case("system", sys2, 2, NULL, 0, MYNAH_SLM_THINK_OFF);

    render_case("tools_one", &user, 1, &WEATHER, 1, MYNAH_SLM_THINK_OFF);

    mynah_slm_message sys_w[2] = {
        { MYNAH_SLM_ROLE_SYSTEM, "You are terse.",     NULL, 0 },
        { MYNAH_SLM_ROLE_USER,   "Weather in Verona?", NULL, 0 },
    };
    render_case("tools_system", sys_w, 2, &WEATHER, 1, MYNAH_SLM_THINK_OFF);

    mynah_slm_message ping_msg = { MYNAH_SLM_ROLE_USER, "ping please", NULL, 0 };
    render_case("tools_bare", &ping_msg, 1, &PING, 1, MYNAH_SLM_THINK_ON);

    mynah_slm_message two_msg = { MYNAH_SLM_ROLE_USER, "Weather in Verona, then ping.", NULL, 0 };
    render_case("tools_two", &two_msg, 1, both, 2, MYNAH_SLM_THINK_ON);

    /* The round trip. `arguments` is JSON text, passed through untouched. */
    mynah_slm_tool_call verona = { "get_weather", (char *)"{\"city\": \"Verona\"}" };
    mynah_slm_tool_call trento = { "get_weather", (char *)"{\"city\": \"Trento\"}" };

    mynah_slm_message rt[3] = {
        { MYNAH_SLM_ROLE_USER,      "What is the weather in Verona?", NULL, 0 },
        { MYNAH_SLM_ROLE_ASSISTANT, "",                               &verona, 1 },
        { MYNAH_SLM_ROLE_TOOL,      "{\"temp_c\": 18, \"sky\": \"clear\"}", NULL, 0 },
    };
    render_case("roundtrip", rt, 3, &WEATHER, 1, MYNAH_SLM_THINK_OFF);

    const mynah_slm_tool_call pair[2] = { verona, trento };
    mynah_slm_message par[4] = {
        { MYNAH_SLM_ROLE_USER,      "Weather in Verona and Trento?", NULL, 0 },
        { MYNAH_SLM_ROLE_ASSISTANT, "",                              pair, 2 },
        { MYNAH_SLM_ROLE_TOOL,      "{\"temp_c\": 18}",              NULL, 0 },
        { MYNAH_SLM_ROLE_TOOL,      "{\"temp_c\": 15}",              NULL, 0 },
    };
    render_case("parallel", par, 4, &WEATHER, 1, MYNAH_SLM_THINK_OFF);

    mynah_slm_message tc[3] = {
        { MYNAH_SLM_ROLE_USER,      "Check Verona.",        NULL, 0 },
        { MYNAH_SLM_ROLE_ASSISTANT, "Let me look that up.", &verona, 1 },
        { MYNAH_SLM_ROLE_TOOL,      "{\"temp_c\": 18}",     NULL, 0 },
    };
    render_case("text_and_call", tc, 3, &WEATHER, 1, MYNAH_SLM_THINK_OFF);

    /* A NULL content is only legal on a turn that carried calls instead. */
    mynah_slm_message bad = { MYNAH_SLM_ROLE_USER, NULL, NULL, 0 };
    check("a message with no content is rejected",
          mynah_slm_render_chat_tools(&bad, 1, NULL, 0, MYNAH_SLM_THINK_OFF, NULL, 0) < 0,
          "rendered a message that has nothing in it");
}

/* ── parsing what the model emits ──────────────────────────────────────────*/

static void parse_case(const char *what, const char *text, long want_calls,
                       size_t want_blocks, const char *want_name,
                       const char *want_args) {
    mynah_slm_tool_call calls[8];
    size_t blocks = 0;
    const long n = mynah_slm_tool_calls_parse(text, strlen(text), calls, 8, &blocks);

    char detail[512];
    snprintf(detail, sizeof detail, "got %ld call(s) in %zu block(s): name=%s args=%s",
             n, blocks, n > 0 ? calls[0].name : "-",
             n > 0 && calls[0].arguments ? calls[0].arguments : "-");

    int ok = (n == want_calls) && (blocks == want_blocks);
    if (ok && want_name)  ok = n > 0 && !strcmp(calls[0].name, want_name);
    if (ok && want_args)  ok = n > 0 && calls[0].arguments && !strcmp(calls[0].arguments, want_args);
    check(what, ok, detail);

    mynah_slm_tool_calls_free(calls, (size_t)(n > 0 ? (n < 8 ? n : 8) : 0));
}

static void test_parsing(void) {
    /* The bare shape: what the tool channel hands over, markers consumed. */
    parse_case("bare JSON from the tool channel",
               "\n{\"name\": \"get_weather\", \"arguments\": {\"city\": \"Verona\"}}\n",
               1, 1, "get_weather", "{\"city\": \"Verona\"}");

    /* The wrapped shape: what a caller who never split the channels has. */
    parse_case("wrapped in <tool_call> markers",
               "<tool_call>\n{\"name\": \"ping\", \"arguments\": {}}\n</tool_call>",
               1, 1, "ping", "{}");

    parse_case("two calls in one turn",
               "<tool_call>\n{\"name\": \"a\", \"arguments\": {}}\n</tool_call>\n"
               "<tool_call>\n{\"name\": \"b\", \"arguments\": {}}\n</tool_call>",
               2, 2, "a", "{}");

    /* Prose around a wrapped call must not become arguments, and a brace in
     * that prose must not become a call of its own. */
    parse_case("prose around a call is ignored",
               "Sure, I will check. {not a call}\n"
               "<tool_call>\n{\"name\": \"ping\", \"arguments\": {}}\n</tool_call>\n"
               "Anything else?",
               1, 1, "ping", "{}");

    /* Nested objects and a string containing a brace: the scanner must not
     * end the object early. */
    parse_case("nested objects and braces inside strings",
               "<tool_call>\n{\"name\": \"f\", \"arguments\": {\"q\": \"a } b\", "
               "\"deep\": {\"x\": [1, 2, {\"y\": 3}]}}}\n</tool_call>",
               1, 1, "f", "{\"q\": \"a } b\", \"deep\": {\"x\": [1, 2, {\"y\": 3}]}}");

    /* Stringified arguments — OpenAI's own wire format, and what several
     * fine-tunes emit. */
    parse_case("stringified arguments are accepted",
               "<tool_call>\n{\"name\": \"f\", \"arguments\": \"{\\\"city\\\": \\\"Verona\\\"}\"}\n</tool_call>",
               1, 1, "f", "{\"city\": \"Verona\"}");

    /* Missing arguments is a no-argument call, not an error. */
    parse_case("a call with no arguments key",
               "<tool_call>\n{\"name\": \"now\"}\n</tool_call>", 1, 1, "now", "{}");

    /* The failures. Each must be COUNTED as an attempted block and produce no
     * call: a caller executes these, so a guess is worse than nothing. */
    parse_case("truncated JSON yields nothing, but is counted",
               "<tool_call>\n{\"name\": \"f\", \"arguments\": {\"city\": \"Ver",
               0, 1, NULL, NULL);
    parse_case("a call with no name is rejected",
               "<tool_call>\n{\"arguments\": {}}\n</tool_call>", 0, 1, NULL, NULL);
    parse_case("scalar arguments are rejected",
               "<tool_call>\n{\"name\": \"f\", \"arguments\": 42}\n</tool_call>", 0, 1, NULL, NULL);
    parse_case("a string that is not an object is rejected",
               "<tool_call>\n{\"name\": \"f\", \"arguments\": \"Verona\"}\n</tool_call>", 0, 1, NULL, NULL);
    parse_case("text with no call at all",
               "The weather in Verona is clear.", 0, 0, NULL, NULL);

    /* One good call and one broken one: the good one survives and the loss is
     * still visible in the block count. */
    parse_case("a broken call does not take a good one with it",
               "<tool_call>\n{\"name\": \"a\", \"arguments\": {}}\n</tool_call>\n"
               "<tool_call>\n{\"name\": }\n</tool_call>",
               1, 2, "a", "{}");
}

/* ── the wire format, both ways ────────────────────────────────────────────*/

static void test_wire(void) {
    mynah_slm_tool_call calls[2] = {
        { "get_weather", (char *)"{\"city\": \"Verona\"}" },
        { "ping",        (char *)"{}" },
    };

    const size_t need = mynah_slm_tool_calls_to_json(calls, 2, NULL, 0);
    char *js = malloc(need + 1);
    const size_t wrote = mynah_slm_tool_calls_to_json(calls, 2, js, need + 1);
    check("to_json sizing pass matches the write", wrote == need && strlen(js) == need, js);

    /* arguments must be a STRING on the wire, so the object has to come back
     * escaped — a client parsing this expects to json.loads it a second time. */
    check("arguments are escaped into a JSON string",
          strstr(js, "\"arguments\":\"{\\\"city\\\": \\\"Verona\\\"}\"") != NULL, js);
    check("each call carries an index for streaming clients",
          strstr(js, "\"index\":0") && strstr(js, "\"index\":1"), js);

    /* Round trip: the array we emit is an array we can read back, which is
     * exactly what a client replaying a previous turn sends us. */
    mynah_slm_tool_call back[2];
    const long n = mynah_slm_tool_calls_from_json(js, strlen(js), back, 2);
    check("the emitted array parses back", n == 2, js);
    if (n == 2) {
        check("round trip keeps the name", !strcmp(back[0].name, "get_weather"), back[0].name);
        check("round trip keeps the arguments",
              !strcmp(back[0].arguments, "{\"city\": \"Verona\"}"), back[0].arguments);
        mynah_slm_tool_calls_free(back, 2);
    }
    free(js);
}

/* ── the tool set a client sends ───────────────────────────────────────────*/

static void test_tool_set(void) {
    char err[256];

    const char *openai =
        "[{\"type\": \"function\", \"function\": {\"name\": \"get_weather\", "
        "\"description\": \"d\", \"parameters\": {\"type\": \"object\"}}}]";
    mynah_slm_tool_set *s = mynah_slm_tools_parse(openai, strlen(openai), err, sizeof err);
    check("OpenAI-shaped tools parse", s != NULL, err);
    if (s) {
        const mynah_slm_tool *t = mynah_slm_tools_items(s);
        check("name, description and schema survive",
              mynah_slm_tools_count(s) == 1 && !strcmp(t[0].name, "get_weather") &&
              !strcmp(t[0].description, "d") && !strcmp(t[0].parameters, "{\"type\": \"object\"}"),
              t[0].name);
        mynah_slm_tools_free(s);
    }

    /* The schema is passed through as WRITTEN — spacing included. Reformatting
     * it would silently move the prompt away from what HF renders. */
    const char *compact = "[{\"name\": \"f\", \"parameters\": {\"a\":1,   \"b\":2}}]";
    s = mynah_slm_tools_parse(compact, strlen(compact), err, sizeof err);
    check("a flat tool (no \"function\" wrapper) is accepted", s != NULL, err);
    if (s) {
        check("the schema is passed through verbatim",
              !strcmp(mynah_slm_tools_items(s)[0].parameters, "{\"a\":1,   \"b\":2}"),
              mynah_slm_tools_items(s)[0].parameters);
        mynah_slm_tools_free(s);
    }

    const char *no_name = "[{\"description\": \"nameless\"}]";
    check("a tool with no name is refused, with a reason",
          mynah_slm_tools_parse(no_name, strlen(no_name), err, sizeof err) == NULL && err[0],
          err);

    const char *broken = "[{\"name\": ";
    check("malformed JSON is refused, with a reason",
          mynah_slm_tools_parse(broken, strlen(broken), err, sizeof err) == NULL && err[0],
          err);

    check("an empty array is refused",
          mynah_slm_tools_parse("[]", 2, err, sizeof err) == NULL, err);
}

int main(int argc, char **argv) {
    const char *fixture = argc > 1 ? argv[1] : "tests/fixtures/chat_tools.txt";

    if (load_fixture(fixture) != 0) {
        printf("FAIL cannot open %s (uv run --extra fixtures python "
               "gen_chat_fixture.py)\n", fixture);
        return 1;
    }
    printf("     %zu rendering cases from %s\n\n", n_fx, fixture);

    test_rendering();
    printf("\n");
    test_parsing();
    printf("\n");
    test_wire();
    printf("\n");
    test_tool_set();

    for (size_t i = 0; i < n_fx; i++) { free(fx_name[i]); free(fx_text[i]); }

    printf("\n%s (%d check%s, %d failure%s)\n", failures ? "FAILED" : "PASS",
           checks, checks == 1 ? "" : "s", failures, failures == 1 ? "" : "s");
    return failures ? 1 : 0;
}
