"""Generate src/unicode_tables.inc — the codepoint ranges the pre-tokenizer needs.

The Qwen2 pre-tokenizer splits on a regex containing \\p{L} and \\p{N}. Getting
those wrong is not a crash, it is a different tokenization for some languages
and identical output for English, which is the worst way for a multilingual
engine to be broken.

So the tables are not hand-written: they are extracted from Python's own
unicodedata, the same way ingot generates its IQ codebooks from llama.cpp's
package rather than typing them in. Run this when the Unicode version moves;
the output is committed, and nothing at runtime needs Python.

    uv run python gen_unicode_tables.py > ../src/unicode_tables.inc
"""

from __future__ import annotations

import sys
import unicodedata

MAX_CP = 0x110000


def ranges_for(predicate) -> list[tuple[int, int]]:
    """Collapse matching codepoints into [start, end] runs."""
    out: list[list[int]] = []
    for cp in range(MAX_CP):
        # Surrogates have no meaningful category and chr() on them is fine, but
        # they cannot appear in valid UTF-8 input anyway.
        if 0xD800 <= cp <= 0xDFFF:
            continue
        if not predicate(cp):
            continue
        if out and out[-1][1] == cp - 1:
            out[-1][1] = cp
        else:
            out.append([cp, cp])
    return [(a, b) for a, b in out]


def emit(name: str, rngs: list[tuple[int, int]]) -> None:
    print(f"/* {name}: {len(rngs)} ranges */")
    print(f"static const uint32_t {name}[][2] = {{")
    for i in range(0, len(rngs), 4):
        chunk = "".join(f" {{0x{a:04X},0x{b:04X}}}," for a, b in rngs[i:i + 4])
        print("   " + chunk)
    print("};")
    print(f"#define {name.upper()}_COUNT ((int)(sizeof({name}) / sizeof({name}[0])))")
    print()


def main() -> int:
    cat = {}
    for cp in range(MAX_CP):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        cat[cp] = unicodedata.category(chr(cp))

    print("/* Generated by tools/gen_unicode_tables.py — do not edit.")
    print(f" * Unicode {unicodedata.unidata_version}, via Python's unicodedata.")
    print(" *")
    print(" * The Qwen2 pre-tokenizer regex needs \\p{L} and \\p{N}. Hand-written")
    print(" * approximations of those are correct for English and wrong for")
    print(" * somebody's language, which is not a trade a multilingual engine can")
    print(" * make. Regenerate rather than patch. */")
    print()

    emit("uc_letter_ranges", ranges_for(lambda cp: cat[cp].startswith("L")))
    emit("uc_number_ranges", ranges_for(lambda cp: cat[cp].startswith("N")))
    # \s in the Rust regex crate is the Unicode White_Space property, and
    # nothing else. Python's str.isspace() is NOT the same set — it also
    # returns True for the C0 controls 0x1C..0x1F — so the property is
    # enumerated here rather than approximated. It is 25 codepoints; guessing
    # would trade a day of debugging for four saved lines.
    WHITE_SPACE = set(range(0x09, 0x0E)) | {
        0x20, 0x85, 0xA0, 0x1680, 0x2028, 0x2029, 0x202F, 0x205F, 0x3000,
    } | set(range(0x2000, 0x200B))
    emit("uc_space_ranges", ranges_for(lambda cp: cp in WHITE_SPACE))
    return 0


if __name__ == "__main__":
    sys.exit(main())
